# Site settings
title: Kat's Profile
email: kat.mierek@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Learn to use GitHub pages with Wheelhouse.io and Patchwork!
baseurl: "/project-gh-pages"
url: "http://katmierek.github.io"
github_username:  katmierek



# Build settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM

collections:
    - index
